export const AUTHORIZATION_SUCCESS = "AUTHORIZATION_SUCCESS";
export const AUTHORIZATION_FAIL = "AUTHORIZATION_FAIL";

export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAIL = "LOG_IN_FAIL";

export const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS";
export const LOG_OUT_FAIL = "LOG_OUT_FAIL";

export const FETCH_STREAMINGS_SUCCESS = "FETCH_STREAMINGS_SUCCESS";
export const FETCH_STREAMINGS_FAIL = "FETCH_STREAMINGS_FAIL";

export const GENERATE_STREAMING_SUCESS = "GENERATE_STREAMING_SUCESS";
export const GENERATE_STREAMING_FAIL = "GENERATE_STREAMING_FAIL";

export const REMOVE_STREAMING_SUCCESS = "REMOVE_STREAMING_SUCCESS";
export const REMOVE_STREAMING_FAIL = "REMOVE_STREAMING_FAIL";

export const UPDATE_USER_NAME_SUCCESS = "UPDATE_USER_NAME_SUCCESS";
export const UPDATE_USER_NAME_FAIL = "UPDATE_USER_NAME_FAIL";

export const SEARCH_USERS_SUCCESS = "SEARCH_USERS_SUCCESS";
export const SEARCH_USERS_FAIL = "SEARCH_USERS_FAIL";
