export const AUTHORIZATION_SUCCESS = "AUTHORIZATION_SUCCESS";
export const AUTHORIZATION_FAIL = "AUTHORIZATION_FAIL";

export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAIL = "LOG_IN_FAIL";

export const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS";
export const LOG_OUT_FAIL = "LOG_OUT_FAIL";

export const FETCH_STREAMINGS_SUCCESS = "FETCH_STREAMINGS_SUCCESS";
export const FETCH_STREAMINGS_FAIL = "FETCH_STREAMINGS_FAIL";
